---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bogdandabeast-custom-os
description: Mi sistema de trabajo
base-image: ghcr.io/ublue-os/bluefin:latest
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /       # Copia todo lo que esté en 'system' a la raíz de la imagen

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-41/atim-starship-fedora-41.repo
    install:
      - micro
      - starship
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.mozilla.firefox
        - org.gnome.Loupe
      remove:
        - org.gnome.eog
    user: {}

  # Módulo para reemplazar el kernel por defecto por el kernel CachyOS
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos/repo/fedora-41/kernel-cachyos-fedora-41.repo
    remove:
      - kernel
      - kernel-core
      - kernel-modules
      - kernel-modules-core
      - kernel-modules-extra
    install:
      - kernel-cachyos

  - type: signing

